title: Cortext
email: boris@cortext.nl
description: >
  I offer consultancy and software development to help Dutch companies leverage
  the data they have using machine learning and artificial intelligence.

twitter_username: breuderink
github_username: breuderink
linkedin_username: breuderink
google_analytics: UA-511603-9

# Build settings
theme: minima
plugins:
  - jekyll-feed
